language: java
install: true
jdk: oraclejdk8
env:
  matrix:
  - TERM=dumb
#  global:
#    secure: LRj23pXG7ikrc/eJ/lcrl+KZ5R7iR1XQVlax7HI/9j6U8abYuIRi0IT34DQwcQSgZB3kXs0bWHxsIR7iz/nCH4S6bDRvImFPKwg20XMdRTbZaREx1eYPy+odXdBf/3BGbmBQ8HLrdxOVTltFWZGvvR49jScQd3z/O8k2FZln43c=
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update -qq
  - sudo apt-get install oracle-java8-installer
before_script:
  - ./gradlew --version
script: ./gradlew -S check test integrationTest functionalTest jacocoTestReport jacocoIntegrationTestReport jacocoFunctionalTestReport jacocoRootReport -x :sample-javafx-java:jfxJar -x :sample-javafx-java:jfxDeploy -x clirr
after_success:
#  - ./update-gh-pages.sh
  - ./gradlew coveralls
  - bash <(curl -s https://codecov.io/bash)
#after_failure:
#  - ./update-gh-pages.sh
