language: java
install: true
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
env:
  matrix:
  - TERM=dumb
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update -qq
  - sudo apt-get install oracle-java8-installer
before_script:
  - ./gradlew --version
script: ./gradlew -S check test integrationTest functionalTest jacocoTestReport jacocoIntegrationTestReport jacocoFunctionalTestReport jacocoRootReport -x :sample-javafx-java:jfxJar -x :sample-javafx-java:jfxDeploy -x clirr
after_success:
  - ./gradlew coveralls
  - bash <(curl -s https://codecov.io/bash)
