version: '{build}'
branches:
  only:
    - master
    - development
  except:
    - gh-pages
skip_tags: true
clone_depth: 10
environment:
  TERM: dumb
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
matrix:
  fast_finish: true
install:
  - gradlew.bat --version
build_script:
  - gradlew.bat -u -i clean
test_script:
  - gradlew.bat -u -i -S test
cache:
  - .gradle
  - C:\Users\appveyor\.gradle
on_failure:
  - echo Somebody setup us the bomb
