= Basilisk
:github-branch: master

image:https://ci.appveyor.com/api/projects/status/s1n73p7bpfu2832s/branch/{github-branch}?svg=true[Build Status (appveyor)", link="https://ci.appveyor.com/project/aalmiray/basilisk/branch/{github-branch}"]
image:http://img.shields.io/travis/basilisk-fw/basilisk/{github-branch}.svg["Build Status (travis)", link="https://travis-ci.org/basilisk-fw/basilisk"]

image:http://img.shields.io/coveralls/basilisk-fw/basilisk/{github-branch}.svg["Coverage Status (coveralls)", link="https://coveralls.io/r/basilisk-fw/basilisk"]
image:https://img.shields.io/codecov/c/github/basilisk-fw/basilisk/{github-branch}.svg["Coverage Status (codecov)", link="https://codecov.io/github/basilisk-fw/basilisk"]

image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"]
image:https://api.bintray.com/packages/basilisk/basilisk/basilisk-core/images/download.svg[Download, link="https://bintray.com/basilisk/basilisk"]

---

image:https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/basilisk-fw/basilisk?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

---

Basilisk is desktop/mobile application development platform
for the JVM. Inspired by http://griffon-framework.org[Griffon], Basilisk leverages JavaFX
and JavafXPorts to bring the same codebase to desktop and mobile platforms alike.

Griffon developers should feel right at home when trying out Basilisk. Many of
Griffon's features and commands are shared with Basilisk.

Seasoned Java developers will also be able to pick up the pace quickly, as the
framework relieves you of the burden of maintaining an application structure,
allowing you to concentrate on getting the code right.


== Quickstart

The recommended way to get started with a Basilisk project is to use a Lazybones project template and Gradle. You can install these tools with SDKMAN.

    $ curl -s http://get.sdkman.io | bash
    $ sdk install lazybones
    $ sdk install gradle

Next register the basilisk-lazybones-templates repository with Lazybones' config file. Edit $USER_HOME/.lazybones/config.groovy

    bintrayRepositories = [
        "basilisk/basilisk-lazybones-templates",
        "pledbrook/lazybones-templates"
    ]

List all available templates by invoking the following command

    $ lazybones list
    Available templates in basilisk/basilisk-lazybones-templates

        basilisk-javafx-ios
        basilisk-plugin

Select a starting template from the list and invoke the create command

    $ lazybones create basilisk-javafx-ios sample

Compile, run and test the project with any of these commands

    $ gradle build
    $ gradle test
    $ gradle run
    $ gradle launchIPhoneSimulator


== Links

- https://github.com/basilisk-fw/basilisk[Home]
- https://github.com/basilisk-fw/basilisk[Documentation]
- https://github.com/basilisk-fw/basilisk[Source]
- https://github.com/basilisk-fw/basilisk/issues[Issue Tracker]
- http://basilisk-user.1128066.n5.nabble.com/[Mailing Lists]
